version: '3.7'

services:
 opsknife_gunicorn:
  volumes:
   - static:/static
  env_file:
   - .env
  build:
   context: .
  ports:
   - "8000:8000"

 nginx:
  build: ./nginx
  volumes:
   - static:/static
  ports:
   - "8080:80"
  depends_on:
   - opsknife_gunicorn

volumes:
 static: